---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtfoundry.io
  resources:
  - instances
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtfoundry.io
  resources:
  - instances/finalizers
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - virtfoundry.io
  resources:
  - instances/status
  - networks/status
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - virtfoundry.io
  resources:
  - networks
  - offerings
  - sshkeys
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virtfoundry.io
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
